include:
  - project: muni-kypo-images/ci-cd-virtual-images
    file: qemu.yml
  - project: muni-kypo-images/ci-cd-virtual-images
    file: vbox.yml

variables:
  NAME: "windows-server-2019"
  TYPE: "windows"
  DISTRO: "windows"

build-qemu:
  before_script:
    - !reference [ .build, before_script ]
    - packer plugins install github.com/rgl/windows-update
    - if [ ! -f virtio-win.iso ]; then
    -  wget -nv https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso -O virtio-win.iso
    - fi
